### PR TITLE
Turning the cucmber tests back on

### PR DESCRIPTION
**Pull request by silverdaz**
Cucumber tests were commented out due to a compilation error.
This turns them back on.

### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### CODE REVIEW

**Comment by nanjiangshu** [comment]
Did I miss something? It seems Bats tests and Cucumber tests were not run on Travis.
https://travis-ci.org/EGA-archive/LocalEGA/jobs/524342387

**Comment by dtitov** [comment]
@nanjiangshu, int-tests are running after merge.

**Comment by dtitov** [comment]
https://travis-ci.org/EGA-archive/LocalEGA/jobs/524331576

**Comment by nanjiangshu** [comment]
I see. Thanks @dtitov 👍

**Pull request merged**
